
# ---------------------------
# General Configuration
# ---------------------------

version: 0.4.{build}

skip_tags: false
skip_non_tags: false

max_jobs: 1

# ---------------------------
# Environment
# ---------------------------

image: Visual Studio 2015

init:
  - git config --global core.autocrlf true
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_depth: 1
environment:
  APPVEYOR_RDP_PASSWORD: Ufida2017!

platform:
  - Win32
  - x64

configuration:
  - Release

build:
  parallel: true
  project: build/ALL_BUILD.vcxproj
  verbosity: normal

before_build:
  - mkdir build
  - cd build
  - 'cmake -DCMAKE_GENERATOR_PLATFORM=%PLATFORM% ..'

#
# Tests
#

test_script:
  - ctest

#
# After
#

artifacts:
  - path: build/src/app-cli/Release/bank-calling-app.exe
    name: bank-calling-app
    type: File

# Deployment
deploy:
  release: bank-calling-${branch}
  description: 'A bank-calling simulation program'
  provider: GitHub
  auth_token:
    secure: wCLCNSQ1gr1PWkBxxhfkeTdWCjdmChy3C/yl0w0iYCB6OThAnJZWUHL442xj77yd
  artifact: bank-calling-app
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
